export const options = [
	{
		id: 'res_small',
		title: '🏠 Residential (small)',
		subtitle: 'for living',
		type: 'residential',
		description: 'A few basic homes (+16 people)',
		revenue_per_week: 0,
		requirements: {
			gold: 150,
			plots: [],
			employees: 0,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.0,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 16,
		},
	},
	{
		id: 'res_medium',
		title: '🏘️ Residential (medium)',
		subtitle: 'for living',
		type: 'residential',
		description: 'Some apartments (+64 people)',
		revenue_per_week: 0,
		requirements: {
			gold: 500,
			plots: [],
			employees: 0,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.0,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 64,
		},
	},
	{
		id: 'res_large',
		title: '🏢 Residential (large)',
		subtitle: 'for living',
		type: 'residential',
		description: 'Many apartments (+256 people)',
		revenue_per_week: 0,
		requirements: {
			gold: 1500,
			plots: [],
			employees: 0,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.0,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 256,
		},
	},
	{
		id: 'carrot_farm',
		title: '🥕 Carrot farm',
		subtitle: 'for farming',
		type: 'farm',
		description: 'Farm for making carrots, makes money by selling them.',
		revenue_per_week: 6,
		requirements: {
			gold: 50,
			plots: [],
			employees: 2,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.05,
			health: 1.1,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 0,
		},
		check_for_variety: true,
	},
	{
		id: 'apple_orchard', // 'apple_orchard
		title: '🍎 Apple orchard',
		subtitle: 'for farming',
		type: 'farm',
		description:
			'A bunch of trees that make apples, makes money by selling them and by selling apple-related products.',
		revenue_per_week: 8,
		requirements: {
			gold: 75,
			plots: [],
			employees: 4,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.05,
			health: 1.1,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 0,
		},
		check_for_variety: true,
	},
	{
		id: 'potato_farm',
		title: '🥔 Potato farm',
		subtitle: 'for farming',
		type: 'farm',
		description: 'Easy to farm, sells to local grocery stores and restaurants.',
		revenue_per_week: 9,
		requirements: {
			gold: 75,
			plots: [],
			employees: 2,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.1,
			health: 1.1,
		},
		immediate_variable_changes: {
			happiness: 5,
			health: 5,
			population: 0,
		},
		check_for_variety: true,
	},
	{
		id: 'dairy_farm',
		title: '🐮 Dairy farm',
		subtitle: 'for farming',
		type: 'farm',
		description: 'A few cows that produce milk, cheese, and butter.',
		revenue_per_week: 16,
		requirements: {
			gold: 300,
			plots: [],
			employees: 4,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.2,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 5,
			health: 5,
			population: 0,
		},
		check_for_variety: true,
	},
	{
		id: 'cafe',
		title: '☕️ Small café',
		subtitle: 'for recreation & food',
		type: 'food',
		description: 'Great for eating & relaxing, not great for long-term health.',
		revenue_per_week: 12,
		requirements: {
			gold: 100,
			plots: [],
			employees: 16,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.05,
			health: 0.95,
		},
		immediate_variable_changes: {
			happiness: 5,
			health: 0,
			population: 0,
		},
		check_for_variety: true,
	},
	{
		id: 'bakery',
		title: '🥖 Bakery',
		subtitle: 'for baking',
		type: 'farm',
		description: 'Makes money by selling bread.',
		revenue_per_week: 12,
		requirements: {
			gold: 100,
			plots: [],
			employees: 3,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.11,
			health: 0.92,
		},
		immediate_variable_changes: {
			happiness: 25,
			health: 0,
			population: 0,
		},
		check_for_variety: true,
	},
	{
		id: 'grocery',
		title: '🏪 Grocery store',
		subtitle: 'for living',
		type: 'food',
		description: 'People get hungry. This is where they go to get food.',
		revenue_per_week: 40,
		requirements: {
			gold: 320,
			plots: [],
			employees: 24,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.05,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 15,
			health: 0,
			population: 0,
		},
	},
	{
		id: 'fishery',
		title: '🐠 Fishery',
		subtitle: 'for fishing',
		type: 'food',
		description:
			'Carve out some land, pour some water, and fish for fun & food.',
		revenue_per_week: 25,
		requirements: {
			gold: 400,
			plots: [],
			employees: 9,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.05,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 15,
			health: 0,
			population: 0,
		},
		check_for_variety: true,
	},
	{
		id: 'library',
		title: '📕 Library',
		subtitle: 'for reading',
		type: 'recreation',
		description: "Reading makes people very happy, but doesn't make money.",
		revenue_per_week: 0,
		knowledge_points_per_month: 1,
		requirements: {
			gold: 500,
			plots: [],
			employees: 6,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.2,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 10,
			health: 0,
			population: 0,
		},
	},
	{
		id: 'pub',
		title: '🍻 Pub',
		subtitle: 'for hanging',
		type: 'recreation',
		description: 'Makes money, and somehow generates communal knowledge.',
		revenue_per_week: 50,
		knowledge_points_per_month: 1,
		requirements: {
			gold: 500,
			plots: [],
			employees: 6,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.2,
			health: 0.7,
		},
		immediate_variable_changes: {
			happiness: 10,
			health: -25,
			population: 0,
		},
		check_for_variety: true,
	},
	{
		id: 'church',
		title: '⛪️ Church',
		subtitle: 'for worship & community',
		type: 'recreation',
		description: "This can make some people happy, but doesn't make money.",
		revenue_per_week: 0,
		requirements: {
			gold: 100,
			plots: [],
			employees: 0,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.1,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 5,
			health: 0,
			population: 0,
		},
	},
	{
		id: 'stables',
		title: '🐴 Stables',
		subtitle: 'for friends',
		type: 'recreation',
		description:
			'People love horses. This makes them happy, and can generate some money through lessons.',
		revenue_per_week: 25,
		requirements: {
			gold: 220,
			plots: [],
			employees: 2,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.05,
			health: 1.02,
		},
		immediate_variable_changes: {
			happiness: 5,
			health: 0,
			population: 0,
		},
	},
	{
		id: 'blacksmith',
		title: '⚔️ Blacksmith',
		subtitle: 'for making shiny things',
		type: 'shop',
		description:
			'Sometimes problems can only be dealt with by a hunk of metal. Makes money by selling weapons, tools, & armor.',
		revenue_per_week: 50,
		requirements: {
			gold: 1300,
			plots: [],
			employees: 13,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 0.9,
			health: 1.5,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 0,
		},
	},
	{
		id: 'vineyard',
		title: '🍇 Vineyard',
		subtitle: '',
		type: 'farm',
		description:
			'Grapes are grown and made into wine. Makes money by selling wine.',
		revenue_per_week: 50,
		requirements: {
			gold: 800,
			plots: [],
			employees: 6,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.5,
			health: 1,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: -10,
			population: 0,
		},
	},
	{
		id: 'inn',
		title: '🛌 Village Inn',
		subtitle: 'for a night out',
		type: 'tourism',
		description: 'Generates tourism gold that can be used if you have a bank.',
		revenue_per_week: 0,
		enables_tourism: true,
		tourism_revenue_per_week: 1, // this is per citizen!
		requirements: {
			gold: 1500,
			plots: [],
			employees: 14,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 0.9,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 0,
		},
	},
	{
		id: 'park_small',
		title: '🌲 Small park',
		subtitle: 'for bringing your dog, or eating a sandwich',
		type: 'recreation',
		description: 'A few benches and a small grassy area.',
		revenue_per_week: 0,
		requirements: {
			gold: 80,
			plots: [],
			employees: 1,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.01,
			health: 1.07,
		},
		immediate_variable_changes: {
			happiness: 5,
			health: 0,
			population: 0,
		},
	},
	{
		id: 'park_medium',
		title: '🛝 Medium park',
		subtitle: 'for bringing your dog, or eating a sandwich',
		type: 'recreation',
		description: 'Benches, grass, and a couple of swing-sets.',
		revenue_per_week: 0,
		requirements: {
			gold: 150,
			plots: [],
			employees: 2,
			climate: null,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.02,
			health: 1.15,
		},
		immediate_variable_changes: {
			happiness: 10,
			health: 0,
			population: 0,
		},
	},
	{
		id: 'park_large',
		title: '🎪 Large park',
		subtitle: 'for bringing your dog, or eating a sandwich',
		type: 'recreation',
		description:
			'Same as the medium park, with a nice fountain in the middle and occasional events run by the employees.',
		revenue_per_week: 0,
		requirements: {
			gold: 300,
			plots: [],
			employees: 4,
			climate: null,
			size: 2,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.09,
			health: 1.25,
		},
		immediate_variable_changes: {
			happiness: 30,
			health: 0,
			population: 0,
		},
	},
	{
		id: 'community_center',
		title: '🫶 Community Center',
		subtitle: 'for community',
		type: 'recreation',
		description:
			'A place for meeting people, growing community, and hosting events. Required for City Hall.',
		revenue_per_week: 0,
		requirements: {
			gold: 5000,
			plots: [],
			employees: 8,
			climate: null,
			size: 1,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.09,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 30,
			health: 0,
			population: 0,
		},
	},
	{
		id: 'small_school',
		title: '📚 Small school',
		subtitle: 'for learning',
		type: 'education',
		description:
			'A place where children can learn and grow, and where adults can learn new skills. Produces knowledge.',
		revenue_per_week: 0,
		knowledge_points_per_month: 8,
		requirements: {
			gold: 1000,
			plots: [],
			employees: 20,
			climate: null,
			size: 1,
			knowledge: 0,
		},
		effect_modifiers: {
			happiness: 1.05,
			health: 1.1,
		},
		immediate_variable_changes: {
			happiness: 15,
			health: 3,
			population: 0,
		},
	},
	{
		id: 'large_school',
		title: '🚌 Large school',
		subtitle: 'for learning',
		type: 'education',
		description: 'A larger school. Produces knowledge',
		revenue_per_week: 0,
		knowledge_points_per_month: 18,
		requirements: {
			gold: 2500,
			plots: [],
			employees: 40,
			climate: null,
			size: 2,
			knowledge: 10,
		},
		effect_modifiers: {
			happiness: 1.05,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 5,
			health: 3,
			population: 0,
		},
	},
	{
		id: 'university',
		title: '🏫 Large University',
		subtitle: 'for learning',
		type: 'education',
		description: 'The supreme learning institution. Produces knowledge.',
		revenue_per_week: 0,
		knowledge_points_per_month: 75,
		requirements: {
			gold: 10000,
			plots: [],
			employees: 64,
			climate: null,
			size: 2,
			knowledge: 100,
		},
		effect_modifiers: {
			happiness: 1.25,
			health: 0.9,
		},
		immediate_variable_changes: {
			happiness: 25,
			health: 25,
			population: 0,
		},
	},
	{
		id: 'small_hospital',
		title: '🚑 Small hospital',
		subtitle: 'for healing',
		type: 'medical',
		description: 'A great place to get fixed up from minor injuries.',
		revenue_per_week: 0,
		knowledge_points_per_month: 0,
		requirements: {
			gold: 5000,
			plots: [],
			employees: 18,
			climate: null,
			size: 1,
			knowledge: 100,
		},
		effect_modifiers: {
			happiness: 1.25,
			health: 1.5,
		},
		immediate_variable_changes: {
			happiness: 5,
			health: 75,
			population: 0,
		},
	},
	{
		id: 'large_hospital',
		title: '🏥 Large hospital',
		subtitle: 'for healing',
		type: 'medical',
		description: 'A great place to get fixed up from all injuries.',
		revenue_per_week: 0,
		knowledge_points_per_month: 0,
		requirements: {
			gold: 10000,
			plots: [],
			employees: 50,
			climate: null,
			size: 1,
			knowledge: 250,
		},
		effect_modifiers: {
			happiness: 1.25,
			health: 2.5,
		},
		immediate_variable_changes: {
			happiness: 5,
			health: 75,
			population: 0,
		},
	},
	{
		id: 'bank',
		title: '🏦 Bank',
		subtitle: 'for storing and accessing funds',
		type: 'bank',
		description: 'Rich get richer.',
		revenue_per_week: 0,
		knowledge_points_per_month: 0,
		requirements: {
			gold: 20000,
			plots: [],
			employees: 64,
			climate: null,
			size: 1,
			knowledge: 300,
		},
		effect_modifiers: {
			happiness: 0.8,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 0,
		},
	},
	{
		id: 'city_hall',
		title: '🗳️ City Hall',
		subtitle: 'for bureaucracy',
		type: 'federal',
		description: 'For running the government.',
		revenue_per_week: 0,
		knowledge_points_per_month: 0,
		requirements: {
			gold: 50000,
			plots: ['community_center'],
			employees: 24,
			climate: null,
			size: 1,
			knowledge: 500,
		},
		effect_modifiers: {
			happiness: 0.8,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 0,
		},
	},
];

export const typeColors = {
	// dark blue
	empty_unusable: 'rgb(21 28 41);',
	empty_buildable: 'rgb(126, 158, 255)',
	residential: '#e15f00',
	farm: '#519c1f',
	food: '#d24646',
	recreation: '#4070ff',
	shop: '#ff00ff',
	tourism: '#ff00ff',
	education: 'rgba(42, 62, 250, 0.9)',
	medical: '#ff0000',
	bank: '#7b68ee',
	federal: '#7b68ee',
};

export function getColor(typeIndex, canBeUpgraded = false) {
	if (typeIndex < 0) {
		if (typeIndex == -1) {
			if (canBeUpgraded) {
				return typeColors['empty_buildable'];
			}
			return typeColors['empty'];
		} else if (typeIndex == -2) {
			return typeColors['education'];
		} else {
			console.log(typeIndex);
			return typeColors['empty'];
		}
	}
	const plotOption = options[typeIndex];
	return typeColors[plotOption.type];
}
