import { PlotOption } from '$lib/types';

export const options: PlotOption[] = [
	{
		id: 'mine',
		title: '⛏️ Mine',
		type: 'mine',
		description: '',
		revenue_per_week: 0,
		requirements: {
			gold: 30000,
			plots: [],
			employees: 85,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.0,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 16,
		},
		tourism_revenue_per_week: 0,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
		enables_tourism: false,
		knowledge_points_per_month: 0,
	},
	{
		id: 'res_small',
		title: '🏠 Small homes',
		type: 'residential',
		description: '+16 people',
		revenue_per_week: 0,
		requirements: {
			gold: 150,
			plots: [],
			employees: 0,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.0,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 16,
		},
		tourism_revenue_per_week: 0,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
		enables_tourism: false,
		knowledge_points_per_month: 0,
	},
	{
		id: 'res_medium',
		title: '🏘️ Residential Complex',
		type: 'residential',
		description: '+64 people',
		revenue_per_week: 0,
		requirements: {
			gold: 500,
			plots: ['tree_farm'],
			employees: 0,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.0,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 64,
		},
		tourism_revenue_per_week: 0,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
		enables_tourism: false,
		knowledge_points_per_month: 0,
	},
	{
		id: 'res_large',
		title: '🏢 Group of homes',
		type: 'residential',
		description: '+256 people',
		revenue_per_week: 0,
		requirements: {
			gold: 1500,
			plots: ['tree_farm'],
			employees: 0,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.0,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 256,
		},
		tourism_revenue_per_week: 0,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
		enables_tourism: false,
		knowledge_points_per_month: 0,
	},
	{
		id: 'tree_farm',
		title: '🌲 Tree Farm',
		type: 'farm',
		description: 'Grow trees and sell the resources. Required for most plots.',
		revenue_per_week: 12,
		requirements: {
			gold: 400,
			plots: [],
			employees: 10,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.0,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 0,
		},
		check_for_variety: true,
		tourism_revenue_per_week: 0,
		styling: '',
		affordable: null,
		selected: null,
		enables_tourism: false,
		knowledge_points_per_month: 0,
	},
	{
		id: 'apple_orchard', // 'apple_orchard
		title: '🍎 Apple orchard',
		type: 'farm',
		description: 'A bunch of apple trees. Sells apple products.',
		revenue_per_week: 8,
		requirements: {
			gold: 75,
			plots: [],
			employees: 4,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.05,
			health: 1.1,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 0,
		},
		check_for_variety: true,
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		knowledge_points_per_month: 0,
		styling: '',
		affordable: null,
		selected: null,
	},
	{
		id: 'potato_and_carrot_farm',
		title: '🚜 Potato & Carrot farm',
		type: 'farm',
		description: 'Easy to farm, sells to local grocery stores and restaurants.',
		revenue_per_week: 9,
		requirements: {
			gold: 75,
			plots: [],
			employees: 2,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.03,
			health: 1.03,
		},
		immediate_variable_changes: {
			happiness: 5,
			health: 5,
			population: 0,
		},
		check_for_variety: true,
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		knowledge_points_per_month: 0,
		styling: '',
		affordable: null,
		selected: null,
	},
	{
		id: 'wheat_farm',
		title: '🌾 Wheat farm',
		type: 'farm',
		description: 'Easy to farm crop',
		revenue_per_week: 12,
		requirements: {
			gold: 140,
			plots: [],
			employees: 4,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.0,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 0,
		},
		check_for_variety: true,
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		knowledge_points_per_month: 0,
		styling: '',
		affordable: null,
		selected: null,
	},
	{
		id: 'bakery',
		title: '🥖 Bakery',
		type: 'business',
		description: 'Makes money by selling bread.',
		revenue_per_week: 14,
		requirements: {
			gold: 300,
			plots: ['wheat_farm'],
			employees: 3,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.11,
			health: 0.92,
		},
		immediate_variable_changes: {
			happiness: 25,
			health: 0,
			population: 0,
		},
		check_for_variety: true,
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		knowledge_points_per_month: 0,
		styling: '',
		affordable: null,
		selected: null,
	},
	{
		id: 'dairy_farm',
		title: '🐮 Dairy farm',
		type: 'farm',
		description: 'A few cows that produce milk, cheese, and butter.',
		revenue_per_week: 16,
		requirements: {
			gold: 300,
			plots: [],
			employees: 4,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.2,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 5,
			health: 5,
			population: 0,
		},
		check_for_variety: true,
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		knowledge_points_per_month: 0,
		styling: '',
		affordable: null,
		selected: null,
	},
	{
		id: 'coffee_bean_farm',
		title: '🫘 Coffee bean farm',
		type: 'farm',
		description: 'A few coffee plants. Makes money by selling coffee.',
		revenue_per_week: 3,
		requirements: {
			gold: 300,
			plots: [],
			employees: 1,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.2,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 5,
			health: 5,
			population: 0,
		},
		check_for_variety: true,
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		knowledge_points_per_month: 0,
		styling: '',
		affordable: null,
		selected: null,
	},
	{
		id: 'cafe',
		title: '☕️ Small café',
		type: 'business',
		description: 'Great for eating & relaxing, not great for long-term health.',
		revenue_per_week: 64,
		requirements: {
			gold: 300,
			plots: ['coffee_bean_farm', 'bakery', 'dairy_farm', 'tree_farm'],
			employees: 16,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.05,
			health: 0.95,
		},
		immediate_variable_changes: {
			happiness: 5,
			health: 0,
			population: 0,
		},
		check_for_variety: true,
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		knowledge_points_per_month: 0,
		styling: '',
		affordable: null,
		selected: null,
	},
	{
		id: 'fishery',
		title: '🐠 Fishery',
		type: 'business',
		description:
			'Carve out some land, pour some water, and fish for fun & food.',
		revenue_per_week: 40,
		requirements: {
			gold: 600,
			plots: ['tree_farm'],
			employees: 9,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.05,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 15,
			health: 8,
			population: 0,
		},
		check_for_variety: true,
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		knowledge_points_per_month: 0,
		styling: '',
		affordable: null,
		selected: null,
	},
	{
		id: 'grocery',
		title: '🏪 Grocery store',
		type: 'business',
		description: 'People get hungry. This is where they go to get food.',
		revenue_per_week: 140,
		requirements: {
			gold: 820,
			plots: [
				'fishery',
				'tree_farm',
				'potato_and_carrot_farm',
				'dairy_farm',
				'bakery',
				'wheat_farm',
				'coffee_bean_farm',
			],
			employees: 24,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.05,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 15,
			health: 0,
			population: 0,
		},
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		knowledge_points_per_month: 0,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
	},
	{
		id: 'library',
		title: '📕 Library',
		type: 'recreation',
		description: "Reading makes people very happy, but doesn't make money.",
		revenue_per_week: 0,
		knowledge_points_per_month: 1,
		requirements: {
			gold: 500,
			plots: ['tree_farm'],
			employees: 6,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.2,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 10,
			health: 0,
			population: 0,
		},
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
	},
	{
		id: 'pub',
		title: '🍻 Pub',
		type: 'recreation',
		description: 'Makes money, and somehow generates communal knowledge.',
		revenue_per_week: 50,
		knowledge_points_per_month: 1,
		requirements: {
			gold: 500,
			plots: ['church', 'tree_farm'],
			employees: 6,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.2,
			health: 0.8,
		},
		immediate_variable_changes: {
			happiness: 10,
			health: -15,
			population: 0,
		},
		check_for_variety: true,
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		styling: '',
		affordable: null,
		selected: null,
	},
	{
		id: 'church',
		title: '⛪️ Church',
		type: 'recreation',
		description: "This can make some people happy, but doesn't make money.",
		revenue_per_week: 0,
		requirements: {
			gold: 500,
			plots: ['tree_farm'],
			employees: 0,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.1,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 5,
			health: 0,
			population: 0,
		},
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		knowledge_points_per_month: 0,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
	},
	{
		id: 'stables',
		title: '🐴 Stables',
		type: 'business',
		description:
			'People love horses. This makes them happy, and can generate some money through lessons.',
		revenue_per_week: 19,
		requirements: {
			gold: 400,
			plots: ['tree_farm'],
			employees: 2,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.05,
			health: 1.02,
		},
		immediate_variable_changes: {
			happiness: 5,
			health: 0,
			population: 0,
		},
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		knowledge_points_per_month: 0,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
	},
	{
		// TODO: Make the blacksmith do a bit more. Also maybe require a mine or something like that if it does more.
		id: 'blacksmith',
		title: '⚔️ Blacksmith',
		type: 'business',
		description:
			'Enables exporting of weapons and armor, and makes money by selling them.',
		revenue_per_week: 150,
		requirements: {
			gold: 3500,
			plots: ['large_school', 'tree_farm', 'mine'],
			employees: 8,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.0,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 0,
		},
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		knowledge_points_per_month: 0,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
	},
	{
		id: 'vineyard',
		title: '🍇 Vineyard',
		type: 'farm',
		description:
			'Grapes are grown and made into wine. Makes money by selling wine.',
		revenue_per_week: 50,
		requirements: {
			gold: 800,
			plots: ['library', 'tree_farm', 'small_school'],
			employees: 6,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.5,
			health: 1,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: -10,
			population: 0,
		},
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		knowledge_points_per_month: 0,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
	},
	{
		id: 'inn',
		title: '🛌 Village Inn',
		type: 'tourism',
		description: 'Generates tourism gold that can be used if you have a bank.',
		revenue_per_week: 0,
		enables_tourism: true,
		tourism_revenue_per_week: 1, // this is per citizen!
		requirements: {
			gold: 30000,
			plots: ['tree_farm', 'cafe', 'stables'],
			employees: 14,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 0.9,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 0,
		},
		knowledge_points_per_month: 0,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
	},
	{
		id: 'park_small',
		title: '🌲 Small park',
		type: 'recreation',
		description: 'A few benches and a small grassy area.',
		revenue_per_week: 0,
		requirements: {
			gold: 190,
			plots: [],
			employees: 1,
			climate: null,
			knowledge: 0,
			size: 1,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.05,
			health: 1.1,
		},
		immediate_variable_changes: {
			happiness: 15,
			health: 15,
			population: 0,
		},
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		knowledge_points_per_month: 0,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
	},
	{
		id: 'park_large',
		title: '🎪 Large park (2x2)',
		type: 'recreation',
		description:
			'Same as the medium park, with a nice fountain in the middle and occasional events run by the employees.',
		revenue_per_week: 0,
		requirements: {
			gold: 900,
			plots: ['tree_farm'],
			employees: 4,
			climate: null,
			size: 2,
			knowledge: 0,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.1,
			health: 1.7,
		},
		immediate_variable_changes: {
			happiness: 15,
			health: 15,
			population: 0,
		},
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		knowledge_points_per_month: 0,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
	},
	{
		id: 'community_center',
		title: '🫶 Community Center',
		type: 'recreation',
		description:
			'A place for meeting people, growing community, and hosting events. Required for City Hall.',
		revenue_per_week: 0,
		requirements: {
			gold: 40000,
			plots: ['inn', 'tree_farm'],
			employees: 12,
			climate: null,
			size: 1,
			knowledge: 0,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.09,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 50,
			health: 15,
			population: 0,
		},
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		knowledge_points_per_month: 0,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
	},
	{
		id: 'small_school',
		title: '📚 Small school',
		type: 'education',
		description:
			'A place where children can learn and grow, and where adults can learn new skills. Produces knowledge.',
		revenue_per_week: 0,
		knowledge_points_per_month: 8,
		requirements: {
			gold: 1500,
			plots: ['tree_farm'],
			employees: 20,
			climate: null,
			size: 1,
			knowledge: 0,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.05,
			health: 1.1,
		},
		immediate_variable_changes: {
			happiness: 15,
			health: 3,
			population: 0,
		},
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
	},
	{
		id: 'large_school',
		title: '🚌 Large school (2x2)',
		type: 'education',
		description: 'A larger school. Produces knowledge',
		revenue_per_week: 0,
		knowledge_points_per_month: 26,
		requirements: {
			gold: 15000,
			plots: ['tree_farm'],
			employees: 40,
			climate: null,
			size: 2,
			knowledge: 50,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.2,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 5,
			health: 3,
			population: 0,
		},
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
	},
	{
		id: 'university',
		title: '🏫 Large University (2x2)',
		type: 'education',
		description: 'The supreme learning institution. Produces knowledge.',
		revenue_per_week: 0,
		knowledge_points_per_month: 300,
		requirements: {
			gold: 80000,
			plots: ['tree_farm'],
			employees: 101,
			climate: null,
			size: 2,
			knowledge: 100,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.25,
			health: 0.9,
		},
		immediate_variable_changes: {
			happiness: 25,
			health: 25,
			population: 0,
		},
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
	},
	{
		id: 'small_hospital',
		title: '😷 Small hospital',
		type: 'medical',
		description: 'A great place to get fixed up from minor injuries.',
		revenue_per_week: 0,
		knowledge_points_per_month: 0,
		requirements: {
			gold: 10000,
			plots: ['tree_farm', 'mine'],
			employees: 18,
			climate: null,
			size: 1,
			knowledge: 100,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.25,
			health: 1.5,
		},
		immediate_variable_changes: {
			happiness: 5,
			health: 75,
			population: 0,
		},
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
	},
	{
		id: 'large_hospital',
		title: '🏥 Large hospital (2x2)',
		type: 'medical',
		description:
			'Heals people and teaches medical students. Produces knowledge.',
		revenue_per_week: 0,
		knowledge_points_per_month: 80,
		requirements: {
			gold: 45000,
			plots: ['tree_farm', 'mine'],
			employees: 90,
			climate: null,
			size: 2,
			knowledge: 250,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 1.25,
			health: 2.5,
		},
		immediate_variable_changes: {
			happiness: 5,
			health: 150,
			population: 0,
		},
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
	},
	{
		id: 'bank',
		title: '🏦 Bank',
		type: 'bank',
		description: `Rich get richer.
			<ul>
				<li>Enables converting tourism gold to gold</li>
				<li>Enables converting knowledge to gold</li>
			</ul>`,
		revenue_per_week: 0,
		knowledge_points_per_month: 0,
		requirements: {
			gold: 75000,
			plots: ['blacksmith', 'vineyard', 'tree_farm'],
			employees: 64,
			climate: null,
			size: 1,
			knowledge: 1000,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 0.8,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 0,
		},
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
	},
	{
		id: 'city_hall',
		title: '🗳️ City Hall',
		type: 'federal',
		description:
			'Enables the control of citizens through laws, taxes, and wealthy men.',
		revenue_per_week: 0,
		knowledge_points_per_month: 0,
		requirements: {
			gold: 150000,
			plots: ['community_center', 'small_school', 'tree_farm'],
			employees: 48,
			climate: null,
			size: 1,
			knowledge: 500,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 0.8,
			health: 1.0,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 0,
		},
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
	},
	{
		id: 'lab',
		title: '🧑‍🔬 Laboratory',
		type: 'science',
		description:
			'Design things that can help your city grow. Experiments can cause unexpected situations. Required to build advanced plot types.',
		revenue_per_week: 0,
		knowledge_points_per_month: 0,
		requirements: {
			gold: 100000,
			plots: ['community_center', 'university', 'mine'],
			employees: 24,
			climate: null,
			size: 1,
			knowledge: 1500,
			xp: 0,
		},
		effect_modifiers: {
			happiness: 0.95,
			health: 0.95,
		},
		immediate_variable_changes: {
			happiness: 0,
			health: 0,
			population: 0,
		},
		tourism_revenue_per_week: 0,
		enables_tourism: false,
		styling: '',
		affordable: null,
		selected: null,
		check_for_variety: false,
	},
];

export const typeColors: any = {
	empty_unusable: 'rgb(21 28 41);',
	empty_buildable: 'rgb(204, 218, 209)',
	residential: '#de7633',
	farm: '#6b8f49',
	business: '#9273a5',
	recreation: '#5277b1',
	shop: '#d896d8',
	tourism: '#d896d8',
	education: '#BFBEEB',
	medical: '#4a5ba3',
	bank: '#8477be',
	federal: '#8477be',
	science: '#4a5ba3',
	mine: '#d9874a',
};

export function getColor(typeIndex: number, canBeUpgraded = false) {
	if (typeIndex < 0) {
		if (typeIndex == -1) {
			if (canBeUpgraded) {
				return typeColors['empty_buildable'];
			}
			return typeColors['empty_unusable'];
		} else if (typeIndex == -2) {
			return typeColors['recreation'];
		} else {
			return typeColors['empty_unusable'];
		}
	}
	const plotOption = options[typeIndex];
	return typeColors[plotOption.type];
}

export const plotTypeMaximums: any = {
	lab: 1,
	city_hall: 1,
	bank: 1,
	community_center: 1,
	inn: 1,
};
